### ISSUE TITLE
Ensure (limited) EPUB 3.3 compliance

### ISSUE THREAD

**Issue by Atulin** [Atulin/EpubMaker#1]
https://www.w3.org/TR/epub-33/

The library should comply with EPUB 3.3 standard. That said, the standard is quite large and has some debatable elements like support for scripting and iframes, so we should be implementing the spec gradually, perhaps not in full.

## Phase 1

- [ ] Support for all necessary metadata
- [ ] Support for cover image
- [ ] Support for title page
- [ ] Support for chapters
- [ ] Support for table of contents
- [ ] Support for embedded images

## Phase 2

- [ ] Support for embedded videos and sounds
- [ ] Support for embedded custom fonts
- [ ] Support for custom CSS styles
